version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    hostname: echo_go
    container_name: echo_go
    volumes:
      - ./:/go/src/github.com/bushiyama/echo_go
    working_dir: /go/src/github.com/bushiyama/echo_go
    environment:
      - GOPATH=/go
    ports:
      - "8080:8080"
